public with sharing class EnvioConstantes {
   public static final String NOFECHA = 'Falta por rellenar la fecha de envio.';
   public static final String NOPRODUCTO = 'Falta por rellenar el id de producto.';
   public static final String NODESCRIPCION = 'Falta por rellenar la descripcion del producto.';
   public static final String NOCANTIDAD = 'Falta por rellenar la cantidad.';
   public static final String NOALMACEN = 'Falta por rellenar el almacen de destino.';
   public static final String ALMACENINCORRECTO = 'El almacen de destino es incorrecto.';
   public static final Integer CODEOK = 200;
   public static final Integer CODEKO = 400;
   public static final String MSGOK = 'La solicitud ha llegado correctamente.';
}
